### ISSUE TITLE
Random Command

### ISSUE THREAD

**Issue by UserUnavailable** [rafaelffilho/Anabot-Reborn#21]
Please Bro, I was using your bot a few minutes ago and I wanted a random command, but it have not.

I mean something that returns 0 or 1/True or False, it's useful when you want to decide something but don't care that much about it.

With pleasure, 333, Raqui.

**Comment by rafaelffilho** [comment]
I was thinking about given the bot a range for the random command, like `10, 50` to generate number between `10` and `50`, or just `50` to generate between `1` and `50`.
